<script lang="ts">
  import { goto } from '$app/navigation'
  import { adminBlockUpsertRoute } from '$lib/admin/routes'
  import { adminStore } from '$lib/admin/stores/admin-store.svelte'
  import { formatBlockName } from '$lib/admin/utils'
  import { Badge } from '$lib/components/ui/badge'
  import * as Card from '$lib/components/ui/card'
  import * as Table from '$lib/components/ui/table'
  import { Cuboid } from 'lucide-svelte'

  const blocks = $derived(adminStore.state.blocks)

  function selectBlock(blockId: string) {
    adminStore.selectBlock(blockId)
    goto(adminBlockUpsertRoute(blockId))
  }
</script>

<div class="space-y-6">
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold">Blocks</h1>
      <p class="text-muted-foreground">Manage reusable component blocks</p>
    </div>
  </div>

  <Card.Root>
    <Card.Header>
      <Card.Title>All Blocks</Card.Title>
      <Card.Description>
        {blocks.length} block{blocks.length !== 1 ? 's' : ''} available
      </Card.Description>
    </Card.Header>
    <Card.Content>
      {#if blocks.length === 0}
        <div class="flex flex-col items-center justify-center py-12 text-center">
          <Cuboid class="mb-4 size-12 text-muted-foreground" />
          <h3 class="mb-2 text-lg font-semibold">No blocks yet</h3>
          <p class="text-sm text-muted-foreground">Blocks will be generated by AI in future iterations</p>
        </div>
      {:else}
        <Table.Root>
          <Table.Header>
            <Table.Row>
              <Table.Head>Name</Table.Head>
              <Table.Head>Description</Table.Head>
              <Table.Head>Folder</Table.Head>
              <Table.Head>Component</Table.Head>
            </Table.Row>
          </Table.Header>
          <Table.Body>
            {#each blocks as block (block.id)}
              <Table.Row class="cursor-pointer hover:bg-muted/50" onclick={() => selectBlock(block.id)}>
                <Table.Cell class="font-medium">{formatBlockName(block.name)}</Table.Cell>
                <Table.Cell class="max-w-md truncate">{block.description || '-'}</Table.Cell>
                <Table.Cell>
                  {#if block.folder}
                    <Badge variant="secondary">{block.folder}</Badge>
                  {:else}
                    <span class="text-muted-foreground">-</span>
                  {/if}
                </Table.Cell>
                <Table.Cell>
                  <code class="rounded bg-muted px-2 py-1 text-xs">{block.snippet.componentKey}</code>
                </Table.Cell>
              </Table.Row>
            {/each}
          </Table.Body>
        </Table.Root>
      {/if}
    </Card.Content>
  </Card.Root>
</div>
