import { json, error } from '@sveltejs/kit'
import { writeFile, mkdir } from 'fs/promises'
import { join } from 'path'
import type { RequestHandler } from './$types'

const OUTPUT_DIR = join(process.cwd(), 'src/generated/admin-config')

export const POST: RequestHandler = async ({ request, locals }) => {
  // Check admin auth
  const user = locals.user
  if (!user?.super_admin && !user?.roles?.includes('admin')) {
    throw error(403, 'Forbidden')
  }

  try {
    const data = await request.json()
    const { pages, menus, tenants } = data

    // Ensure output directory exists
    await mkdir(OUTPUT_DIR, { recursive: true })

    // Write configuration files
    await Promise.all([
      writeFile(
        join(OUTPUT_DIR, 'pages.json'),
        JSON.stringify(pages ?? [], null, 2)
      ),
      writeFile(
        join(OUTPUT_DIR, 'menus.json'),
        JSON.stringify(menus ?? [], null, 2)
      ),
      writeFile(
        join(OUTPUT_DIR, 'tenants.json'),
        JSON.stringify(tenants ?? [], null, 2)
      ),
    ])

    // Generate TypeScript index file
    const indexContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by admin panel export
 * Last updated: ${new Date().toISOString()}
 */

import type { BuilderPageConfig, MenuConfig, TenantConfig } from '$lib/admin/types'

import pagesJson from './pages.json'
import menusJson from './menus.json'
import tenantsJson from './tenants.json'

export const pages = pagesJson as BuilderPageConfig[]
export const menus = menusJson as MenuConfig[]
export const tenants = tenantsJson as TenantConfig[]
`

    await writeFile(join(OUTPUT_DIR, 'index.ts'), indexContent)

    return json({ success: true, message: 'Configuration exported successfully' })
  } catch (e) {
    console.error('Export failed:', e)
    throw error(500, `Export failed: ${e}`)
  }
}
